drop schema if exists task_10 cascade;
create schema task_10;

create table task_10.varchar_last_table
(
    bigint_column_00 bigint,
    bigint_column_01 bigint,
    bigint_column_02 bigint,
    bigint_column_03 bigint,
    bigint_column_04 bigint,
    bigint_column_05 bigint,
    bigint_column_06 bigint,
    bigint_column_07 bigint,
    bigint_column_08 bigint,
    bigint_column_09 bigint,

    bigint_column_10 bigint,
    bigint_column_11 bigint,
    bigint_column_12 bigint,
    bigint_column_13 bigint,
    bigint_column_14 bigint,
    bigint_column_15 bigint,
    bigint_column_16 bigint,
    bigint_column_17 bigint,
    bigint_column_18 bigint,
    bigint_column_19 bigint,

    bigint_column_20 bigint,
    bigint_column_21 bigint,
    bigint_column_22 bigint,
    bigint_column_23 bigint,
    bigint_column_24 bigint,
    bigint_column_25 bigint,
    bigint_column_26 bigint,
    bigint_column_27 bigint,
    bigint_column_28 bigint,
    bigint_column_29 bigint,

    bigint_column_30 bigint,
    bigint_column_31 bigint,
    bigint_column_32 bigint,
    bigint_column_33 bigint,
    bigint_column_34 bigint,
    bigint_column_35 bigint,
    bigint_column_36 bigint,
    bigint_column_37 bigint,
    bigint_column_38 bigint,
    bigint_column_39 bigint,

    bigint_column_40 bigint,
    bigint_column_41 bigint,
    bigint_column_42 bigint,
    bigint_column_43 bigint,
    bigint_column_44 bigint,
    bigint_column_45 bigint,
    bigint_column_46 bigint,
    bigint_column_47 bigint,
    bigint_column_48 bigint,
    bigint_column_49 bigint,

    bigint_column_50 bigint,
    bigint_column_51 bigint,
    bigint_column_52 bigint,
    bigint_column_53 bigint,
    bigint_column_54 bigint,
    bigint_column_55 bigint,
    bigint_column_56 bigint,
    bigint_column_57 bigint,
    bigint_column_58 bigint,
    bigint_column_59 bigint,

    bigint_column_60 bigint,
    bigint_column_61 bigint,
    bigint_column_62 bigint,
    bigint_column_63 bigint,
    bigint_column_64 bigint,
    bigint_column_65 bigint,
    bigint_column_66 bigint,
    bigint_column_67 bigint,
    bigint_column_68 bigint,
    bigint_column_69 bigint,

    bigint_column_70 bigint,
    bigint_column_71 bigint,
    bigint_column_72 bigint,
    bigint_column_73 bigint,
    bigint_column_74 bigint,
    bigint_column_75 bigint,
    bigint_column_76 bigint,
    bigint_column_77 bigint,
    bigint_column_78 bigint,
    bigint_column_79 bigint,

    bigint_column_80 bigint,
    bigint_column_81 bigint,
    bigint_column_82 bigint,
    bigint_column_83 bigint,
    bigint_column_84 bigint,
    bigint_column_85 bigint,
    bigint_column_86 bigint,
    bigint_column_87 bigint,
    bigint_column_88 bigint,
    bigint_column_89 bigint,

    bigint_column_90 bigint,
    bigint_column_91 bigint,
    bigint_column_92 bigint,
    bigint_column_93 bigint,
    bigint_column_94 bigint,
    bigint_column_95 bigint,
    bigint_column_96 bigint,
    bigint_column_97 bigint,
    bigint_column_98 bigint,
    bigint_column_99 bigint,

    varchar_column varchar(256)
);

create table task_10.varchar_first_table
(
    varchar_column varchar(256),
    
    bigint_column_00 bigint,
    bigint_column_01 bigint,
    bigint_column_02 bigint,
    bigint_column_03 bigint,
    bigint_column_04 bigint,
    bigint_column_05 bigint,
    bigint_column_06 bigint,
    bigint_column_07 bigint,
    bigint_column_08 bigint,
    bigint_column_09 bigint,

    bigint_column_10 bigint,
    bigint_column_11 bigint,
    bigint_column_12 bigint,
    bigint_column_13 bigint,
    bigint_column_14 bigint,
    bigint_column_15 bigint,
    bigint_column_16 bigint,
    bigint_column_17 bigint,
    bigint_column_18 bigint,
    bigint_column_19 bigint,

    bigint_column_20 bigint,
    bigint_column_21 bigint,
    bigint_column_22 bigint,
    bigint_column_23 bigint,
    bigint_column_24 bigint,
    bigint_column_25 bigint,
    bigint_column_26 bigint,
    bigint_column_27 bigint,
    bigint_column_28 bigint,
    bigint_column_29 bigint,

    bigint_column_30 bigint,
    bigint_column_31 bigint,
    bigint_column_32 bigint,
    bigint_column_33 bigint,
    bigint_column_34 bigint,
    bigint_column_35 bigint,
    bigint_column_36 bigint,
    bigint_column_37 bigint,
    bigint_column_38 bigint,
    bigint_column_39 bigint,

    bigint_column_40 bigint,
    bigint_column_41 bigint,
    bigint_column_42 bigint,
    bigint_column_43 bigint,
    bigint_column_44 bigint,
    bigint_column_45 bigint,
    bigint_column_46 bigint,
    bigint_column_47 bigint,
    bigint_column_48 bigint,
    bigint_column_49 bigint,

    bigint_column_50 bigint,
    bigint_column_51 bigint,
    bigint_column_52 bigint,
    bigint_column_53 bigint,
    bigint_column_54 bigint,
    bigint_column_55 bigint,
    bigint_column_56 bigint,
    bigint_column_57 bigint,
    bigint_column_58 bigint,
    bigint_column_59 bigint,

    bigint_column_60 bigint,
    bigint_column_61 bigint,
    bigint_column_62 bigint,
    bigint_column_63 bigint,
    bigint_column_64 bigint,
    bigint_column_65 bigint,
    bigint_column_66 bigint,
    bigint_column_67 bigint,
    bigint_column_68 bigint,
    bigint_column_69 bigint,

    bigint_column_70 bigint,
    bigint_column_71 bigint,
    bigint_column_72 bigint,
    bigint_column_73 bigint,
    bigint_column_74 bigint,
    bigint_column_75 bigint,
    bigint_column_76 bigint,
    bigint_column_77 bigint,
    bigint_column_78 bigint,
    bigint_column_79 bigint,

    bigint_column_80 bigint,
    bigint_column_81 bigint,
    bigint_column_82 bigint,
    bigint_column_83 bigint,
    bigint_column_84 bigint,
    bigint_column_85 bigint,
    bigint_column_86 bigint,
    bigint_column_87 bigint,
    bigint_column_88 bigint,
    bigint_column_89 bigint,

    bigint_column_90 bigint,
    bigint_column_91 bigint,
    bigint_column_92 bigint,
    bigint_column_93 bigint,
    bigint_column_94 bigint,
    bigint_column_95 bigint,
    bigint_column_96 bigint,
    bigint_column_97 bigint,
    bigint_column_98 bigint,
    bigint_column_99 bigint
);